version: "3.7"
services:
  nginx-proxy:
    image: nginx:alpine
    ports: 
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
  mariadb:
    image: yobasystems/alpine-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: webshop
    volumes:
      - ./mysql-dump/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: jackgruber/phpmyadmin
    ports:
      - "5000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
volumes:
  mysql-data: