version: "3.7"
services:
  nginx-proxy:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    ports: 
      - "80:80"
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
    #command: copy -r /var/composer/vendor /var/www/html/vendor
    #command: sh /var/initPhp.sh
  mariadb:
    image: yobasystems/alpine-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: webshop
    volumes:
      - ./mysql-dump/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: jackgruber/phpmyadmin
    ports:
      - "5000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      #PMA_USER: root
      #PMA_PASSWORD: secret
    depends_on:
      - mariadb
volumes:
  mysql-data: